import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TransitionAnimation from "@/components/page-transition/TransitionAnimation";
import PageContent from "@/components/page-transition/PageContent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Vorhänge sind IMMER da (versteckt bei y: -100%), 
            damit TransitionLink sie finden kann */}
        <TransitionAnimation />
        
        {/* Wrapper für sanften Fade-in bei jedem Seitenwechsel */}
        <PageContent>
          {children}
        </PageContent>
      </body>
    </html>
  );
}
